name: Run Integration Tests

on:
  push:
    branches:
      - deployment

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        
      - name: Build Docker image
        run: docker build -t my-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-image dietmanagment/diet
          docker push dietmanagment/diet

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run tests
        run: |
          docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit test

      - name: Clean up
        run: docker-compose -f docker-compose-test.yml down
